//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrasatHealthMobile.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DrasatHealthMobile.Languages.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking date.
        /// </summary>
        internal static string AddBooking_BookingDate {
            get {
                return ResourceManager.GetString("AddBooking_BookingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BookingReason.
        /// </summary>
        internal static string AddBooking_BookingReason {
            get {
                return ResourceManager.GetString("AddBooking_BookingReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string AddBooking_btn_Submit {
            get {
                return ResourceManager.GetString("AddBooking_btn_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period:.
        /// </summary>
        internal static string AddBooking_Period {
            get {
                return ResourceManager.GetString("AddBooking_Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        internal static string AddBooking_TheDate {
            get {
                return ResourceManager.GetString("AddBooking_TheDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment Booking.
        /// </summary>
        internal static string AddBooking_TitlePage {
            get {
                return ResourceManager.GetString("AddBooking_TitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visiting fees:.
        /// </summary>
        internal static string AddBooking_VisitingFees {
            get {
                return ResourceManager.GetString("AddBooking_VisitingFees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string BookingDetails_btn_cancel {
            get {
                return ResourceManager.GetString("BookingDetails_btn_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clinic.
        /// </summary>
        internal static string BookingDetails_Clinic {
            get {
                return ResourceManager.GetString("BookingDetails_Clinic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient name.
        /// </summary>
        internal static string BookingDetails_PatientName {
            get {
                return ResourceManager.GetString("BookingDetails_PatientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking Details.
        /// </summary>
        internal static string BookingDetails_TitlePage {
            get {
                return ResourceManager.GetString("BookingDetails_TitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type visit.
        /// </summary>
        internal static string BookingDetails_TypeVitst {
            get {
                return ResourceManager.GetString("BookingDetails_TypeVitst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Date.
        /// </summary>
        internal static string BookingDetails_VisitDate {
            get {
                return ResourceManager.GetString("BookingDetails_VisitDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Period.
        /// </summary>
        internal static string BookingDetails_WorkingPeriod {
            get {
                return ResourceManager.GetString("BookingDetails_WorkingPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Future.
        /// </summary>
        internal static string Bookings_Future {
            get {
                return ResourceManager.GetString("Bookings_Future", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can view specialties or doctors and book an appointment.
        /// </summary>
        internal static string Bookings_Goto_docOr_spei {
            get {
                return ResourceManager.GetString("Bookings_Goto_docOr_spei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Past.
        /// </summary>
        internal static string Bookings_Past {
            get {
                return ResourceManager.GetString("Bookings_Past", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        internal static string Bookings_Status {
            get {
                return ResourceManager.GetString("Bookings_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no Booking to view them.
        /// </summary>
        internal static string Bookings_ThereAreNoBooking {
            get {
                return ResourceManager.GetString("Bookings_ThereAreNoBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biography.
        /// </summary>
        internal static string DoctorDetails_Biography {
            get {
                return ResourceManager.GetString("DoctorDetails_Biography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book.
        /// </summary>
        internal static string DoctorDetails_Book {
            get {
                return ResourceManager.GetString("DoctorDetails_Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branches.
        /// </summary>
        internal static string DoctorDetails_Branch {
            get {
                return ResourceManager.GetString("DoctorDetails_Branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read less.
        /// </summary>
        internal static string DoctorDetails_ReadLess {
            get {
                return ResourceManager.GetString("DoctorDetails_ReadLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read more.
        /// </summary>
        internal static string DoctorDetails_ReadMore {
            get {
                return ResourceManager.GetString("DoctorDetails_ReadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no appointments to display.
        /// </summary>
        internal static string DoctorDetails_TherNoData {
            get {
                return ResourceManager.GetString("DoctorDetails_TherNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time table.
        /// </summary>
        internal static string DoctorDetails_Timetable {
            get {
                return ResourceManager.GetString("DoctorDetails_Timetable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor details.
        /// </summary>
        internal static string DoctorDetails_TitlePage {
            get {
                return ResourceManager.GetString("DoctorDetails_TitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both.
        /// </summary>
        internal static string Doctors_BothSexes {
            get {
                return ResourceManager.GetString("Doctors_BothSexes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string Doctors_btn_apply {
            get {
                return ResourceManager.GetString("Doctors_btn_apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The day.
        /// </summary>
        internal static string Doctors_Days {
            get {
                return ResourceManager.GetString("Doctors_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor.
        /// </summary>
        internal static string Doctors_Doctor {
            get {
                return ResourceManager.GetString("Doctors_Doctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female doctor.
        /// </summary>
        internal static string Doctors_FemaleDoctor {
            get {
                return ResourceManager.GetString("Doctors_FemaleDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string Doctors_Filter {
            get {
                return ResourceManager.GetString("Doctors_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string Doctors_Gender {
            get {
                return ResourceManager.GetString("Doctors_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no doctors to display.
        /// </summary>
        internal static string Doctors_ThereNoDoctors {
            get {
                return ResourceManager.GetString("Doctors_ThereNoDoctors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Doctors_Title {
            get {
                return ResourceManager.GetString("Doctors_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try a broader filter.
        /// </summary>
        internal static string Doctors_TryBroaderFilter {
            get {
                return ResourceManager.GetString("Doctors_TryBroaderFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask for help.
        /// </summary>
        internal static string Home_AskHelp {
            get {
                return ResourceManager.GetString("Home_AskHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book a clinic visit.
        /// </summary>
        internal static string Home_BookVisit {
            get {
                return ResourceManager.GetString("Home_BookVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alrahma Hospital.
        /// </summary>
        internal static string Home_hosName {
            get {
                return ResourceManager.GetString("Home_hosName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by name of doctor or specialty.
        /// </summary>
        internal static string Home_SearchByNamrOrDoc {
            get {
                return ResourceManager.GetString("Home_SearchByNamrOrDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to arrow_left.
        /// </summary>
        internal static string Icon_BackButtonArrow {
            get {
                return ResourceManager.GetString("Icon_BackButtonArrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new account.
        /// </summary>
        internal static string Login_CreateNewAcount {
            get {
                return ResourceManager.GetString("Login_CreateNewAcount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address.
        /// </summary>
        internal static string Login_Email {
            get {
                return ResourceManager.GetString("Login_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to did you forget your password?.
        /// </summary>
        internal static string Login_ForgetPass {
            get {
                return ResourceManager.GetString("Login_ForgetPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login_Login {
            get {
                return ResourceManager.GetString("Login_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a password.
        /// </summary>
        internal static string Login_Password {
            get {
                return ResourceManager.GetString("Login_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string public_SelectAll {
            get {
                return ResourceManager.GetString("public_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Register_btn_Next {
            get {
                return ResourceManager.GetString("Register_btn_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Register_btn_Save {
            get {
                return ResourceManager.GetString("Register_btn_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calling code.
        /// </summary>
        internal static string Register_CallingCodes {
            get {
                return ResourceManager.GetString("Register_CallingCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        internal static string Register_ConfirmPassword {
            get {
                return ResourceManager.GetString("Register_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your country.
        /// </summary>
        internal static string Register_Country {
            get {
                return ResourceManager.GetString("Register_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Account.
        /// </summary>
        internal static string Register_CreateAcount {
            get {
                return ResourceManager.GetString("Register_CreateAcount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter an Email.
        /// </summary>
        internal static string Register_Email {
            get {
                return ResourceManager.GetString("Register_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        internal static string Register_FullName {
            get {
                return ResourceManager.GetString("Register_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gender.
        /// </summary>
        internal static string Register_HumanGender {
            get {
                return ResourceManager.GetString("Register_HumanGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marital statuses.
        /// </summary>
        internal static string Register_MaritalStatuses {
            get {
                return ResourceManager.GetString("Register_MaritalStatuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a password.
        /// </summary>
        internal static string Register_Password {
            get {
                return ResourceManager.GetString("Register_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a Phone number.
        /// </summary>
        internal static string Register_PhoneNumber {
            get {
                return ResourceManager.GetString("Register_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        internal static string Register_Privacy {
            get {
                return ResourceManager.GetString("Register_Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I agree to.
        /// </summary>
        internal static string Register_PrivacyAgree {
            get {
                return ResourceManager.GetString("Register_PrivacyAgree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must agree to the privacy policy before creating an account.
        /// </summary>
        internal static string Register_PrivacyMustAgree {
            get {
                return ResourceManager.GetString("Register_PrivacyMustAgree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookings.
        /// </summary>
        internal static string TabBar_booking {
            get {
                return ResourceManager.GetString("TabBar_booking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clinics.
        /// </summary>
        internal static string TabBar_clinics {
            get {
                return ResourceManager.GetString("TabBar_clinics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctors.
        /// </summary>
        internal static string TabBar_doctors {
            get {
                return ResourceManager.GetString("TabBar_doctors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string TabBar_login {
            get {
                return ResourceManager.GetString("TabBar_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string TabBar_logout {
            get {
                return ResourceManager.GetString("TabBar_logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string TabBar_main {
            get {
                return ResourceManager.GetString("TabBar_main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        internal static string TabBar_more {
            get {
                return ResourceManager.GetString("TabBar_more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialties.
        /// </summary>
        internal static string TabBar_specialty {
            get {
                return ResourceManager.GetString("TabBar_specialty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string Template_BottomSheetApply {
            get {
                return ResourceManager.GetString("Template_BottomSheetApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Template_Search_search {
            get {
                return ResourceManager.GetString("Template_Search_search", resourceCulture);
            }
        }
    }
}
